version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamodb-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dgb3stubi5xa"
s3_prefix = "dynamodb-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

